"""add draft col items table

Revision ID: 8d612563da8d
Revises: 0491fbc60b24
Create Date: 2024-01-15 01:22:10.638600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d612563da8d'
down_revision: Union[str, None] = '0491fbc60b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('draft', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'draft')
    # ### end Alembic commands ###
